name: Github Tag Check
description: Checks the code for a version. Compares that version with GitHub.
branding:
  icon: git-merge
  color: blue
author: dudo
inputs:
  version:
    description: Declare this variable if you don't want the version inferred.
    required: false
  git_tag_prefix:
    description: What to use in front of your version? eg. v, ver.
    required: false
  GITHUB_REPOSITORY:
    description: user_or_organization/repo
    required: true
    default: This is provided by GitHub during events.
  GITHUB_TOKEN:
    description: GitHub token.
    required: true
    default: This is provided by GitHub during events.
runs:
  using: docker
  image: Dockerfile
outputs:
  git_tag_name:
    description: The detected tag name.
