on:
  pull_request:
    branches:
      - master
name: Check Version
jobs:
  check_version:
    name: Check Version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INPUT_GIT_TAG_PREFIX: v
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
      - name: Build docker image
        run: docker build -t local .
      - name: Run image
        run: docker run -e INPUT_GIT_TAG_PREFIX -e GITHUB_TOKEN -e GITHUB_REPOSITORY local
